// lib/products.ts
import { Product } from '@/types'; // مطمئن شوید مسیر صحیح است

export const products: Product[] = [
  {
    id: 'EM-HP-001',
    name: 'هدفون حرفه‌ای EMX-Pro',
    category: 'هدفون',
    image: '🎧',
    description: 'هدفون مانیتورینگ حرفه‌ای با کیفیت صدای استودیویی',
    pricePartner2: '2,500,000',
    pricePartner1: '2,800,000',
    priceRegular: '3,200,000',
  },
  {
    id: 'EM-SP-002',
    name: 'اسپیکر خانگی EMX-Home',
    category: 'سیستم خانگی',
    image: '🔊',
    description: 'سیستم صوتی خانگی با قدرت 200 وات و کیفیت Hi-Fi',
    pricePartner2: '4,200,000',
    pricePartner1: '4,600,000',
    priceRegular: '5,200,000',
  },
  {
    id: 'EM-MIC-003',
    name: 'میکروفون استودیویی EMX-Studio',
    category: 'تجهیزات استودیو',
    image: '🎤',
    description: 'میکروفون کندنسر حرفه‌ای برای ضبط استودیویی',
    pricePartner2: '1,800,000',
    pricePartner1: '2,100,000',
    priceRegular: '2,500,000',
  },
  {
    id: 'EM-AMP-004',
    name: 'آمپلی‌فایر EMX-Power',
    category: 'تجهیزات استودیو',
    image: '🎛️',
    description: 'آمپلی‌فایر قدرت 500 وات با کیفیت صدای بی‌نظیر',
    pricePartner2: '6,500,000',
    pricePartner1: '7,200,000',
    priceRegular: '8,500,000',
  },
  {
    id: 'EM-HP-005',
    name: 'هدفون بی‌سیم EMX-Wireless',
    category: 'هدفون',
    image: '🎧',
    description: 'هدفون بلوتوث با نویز کنسلینگ و باتری 30 ساعته',
    pricePartner2: '1,900,000',
    pricePartner1: '2,200,000',
    priceRegular: '2,700,000',
  },
  {
    id: 'EM-SP-006',
    name: 'اسپیکر مانیتور EMX-Monitor',
    category: 'اسپیکر',
    image: '📢',
    description: 'اسپیکر مانیتور استودیویی با پاسخ فرکانسی تخت',
    pricePartner2: '3,800,000',
    pricePartner1: '4,300,000',
    priceRegular: '5,000,000',
  },
];